BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "tbl_BLACKLIST_GROUPS" (
	"UID"	TEXT NOT NULL UNIQUE,
	"NAME"	TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS "tbl_BLACKLIST_GROUPS_CLIENTS" (
	"GROUP_ID"	TEXT NOT NULL,
	"CLIENT_AUTH_TOKEN"	TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS "tbl_BLACKLIST_PACKAGES" (
	"GROUP_ID"	TEXT NOT NULL,
	"PACKAGE_ID"	TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS "tbl_CLIENTS" (
	"UID"	TEXT NOT NULL UNIQUE,
	"NAME"	TEXT,
	"IP"	TEXT,
	"LASTSEEN"	TEXT DEFAULT '',
	"CLIENT"	INTEGER DEFAULT 0,
	"TOKEN"	TEXT NOT NULL,
	"ENABLED"	INTEGER DEFAULT 1,
	PRIMARY KEY("UID")
);
CREATE TABLE IF NOT EXISTS "tbl_CLIENTS_LOGS" (
	"CLIENT_ID"	TEXT NOT NULL,
	"LOG_TYPE"	TEXT NOT NULL,
	"LOG_MESSAGE"	TEXT NOT NULL,
	"TIMESTAMP"	TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS "tbl_CLIENTS_PACKAGES_BLACKLIST" (
	"CLIENT_AUTH_TOKEN"	TEXT NOT NULL,
	"PACKAGE_ID"	TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS "tbl_FIELDS" (
	"FIELD_ID"	TEXT NOT NULL UNIQUE,
	"TEXT"	TEXT,
	"SECTION"	TEXT NOT NULL,
	"LANGUAGE"	TEXT NOT NULL DEFAULT 'EN'
);
CREATE TABLE IF NOT EXISTS "tbl_PACKAGES" (
	"PACKAGE_ID"	TEXT NOT NULL UNIQUE,
	"PACKAGE_NAME"	TEXT NOT NULL,
	"PACKAGE_PUBLISHER"	TEXT NOT NULL,
	"PACKAGE_DESCRIPTION"	TEXT NOT NULL,
	"PACKAGE_LOGO"	TEXT,
	"PACKAGE_ACTIVE"	INTEGER NOT NULL DEFAULT 1,
	PRIMARY KEY("PACKAGE_ID")
);
CREATE TABLE IF NOT EXISTS "tbl_PACKAGES_LOCALE" (
	"LOCALE_ID"	INTEGER NOT NULL UNIQUE,
	"LOCALE"	TEXT NOT NULL,
	PRIMARY KEY("LOCALE_ID" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "tbl_PACKAGES_NESTED" (
	"PACKAGE_VERSION_UID"	TEXT NOT NULL,
	"NAME"	TEXT NOT NULL,
	"PATH"	TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS "tbl_PACKAGES_SWITCHES" (
	"PACKAGE_VERSION_UID"	TEXT NOT NULL,
	"SWITCH_TYPE"	TEXT NOT NULL,
	"SWITCH_TEXT"	TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS "tbl_PACKAGES_VERSIONS" (
	"PACKAGE_ID"	TEXT NOT NULL,
	"VERSION"	TEXT NOT NULL,
	"LOCALE_ID"	INTEGER NOT NULL,
	"ARCHITECTURE"	TEXT NOT NULL,
	"INSTALLER_TYPE"	TEXT NOT NULL,
	"INSTALLER_NESTED_TYPE"	TEXT DEFAULT '',
	"INSTALLER_URL"	TEXT NOT NULL,
	"INSTALLER_SHA256"	TEXT NOT NULL,
	"INSTALLER_SCOPE"	TEXT NOT NULL,
	"UID"	TEXT NOT NULL,
	"PRODUCTCODE"	TEXT DEFAULT '',
	"UPGRADECODE"	TEXT DEFAULT '',
	"PACKAGE_FAMILY_NAME"	TEXT DEFAULT '',
	"CHANNEL"	TEXT DEFAULT 'stable',
	PRIMARY KEY("UID")
);
CREATE TABLE IF NOT EXISTS "tbl_SETTINGS" (
	"SETTING_NAME"	TEXT NOT NULL,
	"VALUE"	TEXT NOT NULL,
	"TYPE"	TEXT NOT NULL DEFAULT 'TEXT',
	"SHOW"	INTEGER DEFAULT 1,
	"MAX_LENGTH"	INTEGER,
	"INTERNET"	INTEGER DEFAULT 0
);
CREATE TABLE IF NOT EXISTS "tbl_TEXTS" (
	"ID"	TEXT NOT NULL UNIQUE,
	"TEXT"	TEXT
);
CREATE TABLE IF NOT EXISTS "tbl_USER" (
	"ID"	TEXT NOT NULL,
	"USERNAME"	TEXT NOT NULL,
	"PW"	TEXT NOT NULL,
	"DELETABLE"	INTEGER NOT NULL DEFAULT 1,
	"GROUP"	TEXT NOT NULL DEFAULT 0,
	PRIMARY KEY("ID")
);
CREATE TABLE IF NOT EXISTS "tbl_USER_API" (
	"UID"	TEXT NOT NULL,
	"TOKEN"	TEXT,
	"TIMESTAMP"	TEXT
);
CREATE TABLE IF NOT EXISTS "tbl_USER_RIGHTS" (
	"ID"	TEXT NOT NULL,
	"NAME"	TEXT NOT NULL,
	"USER_BP.INDEX"	INTEGER NOT NULL DEFAULT 0,
	"USER_BP.ADD_USER"	INTEGER NOT NULL DEFAULT 0,
	"USER_BP.EDIT_USER"	INTEGER NOT NULL DEFAULT 0,
	"USER_BP.CHANGE_PASSWORD"	INTEGER NOT NULL DEFAULT 0,
	"USER_BP.DELETE_USER"	INTEGER NOT NULL DEFAULT 0,
	"UI_BP.ADD_PACKAGE"	INTEGER NOT NULL DEFAULT 0,
	"UI_BP.EDIT_PACKAGE"	INTEGER NOT NULL DEFAULT 0,
	"UI_BP.DELETE_PACKAGE"	INTEGER NOT NULL DEFAULT 0,
	"UI_BP.ADD_PACKAGE_VERSION"	INTEGER NOT NULL DEFAULT 0,
	"UI_BP.DELETE_PACKAGE_VERSION"	INTEGER NOT NULL DEFAULT 0,
	"GROUPS_BP.INDEX"	INTEGER NOT NULL DEFAULT 0,
	"GROUPS_BP.SAVE"	INTEGER NOT NULL DEFAULT 0,
	"GROUPS_BP.ADD_GROUP"	INTEGER NOT NULL DEFAULT 0,
	"GROUPS_BP.DELETE_GROUP"	INTEGER NOT NULL DEFAULT 0,
	"CLIENT_BP.INDEX"	INTEGER NOT NULL DEFAULT 0,
	"CLIENT_BP.ADD_CLIENT"	INTEGER NOT NULL DEFAULT 0,
	"CLIENT_BP.DELETE_CLIENT"	INTEGER NOT NULL DEFAULT 0,
	"SETTINGS_BP.INDEX"	INTEGER NOT NULL DEFAULT 0,
	"SETTINGS_BP.EDIT_TERMS"	INTEGER NOT NULL DEFAULT 0,
	"CLIENT_BP.VIEW_LOGS"	INTEGER NOT NULL DEFAULT 0,
	"CLIENT_BP.CLEAR_LOGS"	INTEGER NOT NULL DEFAULT 0,
	"CLIENT_BP.BLACKLIST"	INTEGER NOT NULL DEFAULT 0,
	"CLIENT_BP.BLACKLIST_GROUPS"	INTEGER NOT NULL DEFAULT 0,
	"CLIENT_BP.BLOCK_CLIENT"	INTEGER NOT NULL DEFAULT 0,
	"STORE_BP.INDEX"	INTEGER NOT NULL DEFAULT 0,
	"STORE_BP.REFRESH_SOURCE"	INTEGER NOT NULL DEFAULT 0,
	"STORE_BP.ADD_PACKAGE"	INTEGER NOT NULL DEFAULT 0,
	"CLIENT_BP.SETUP_CLIENT"	INTEGER NOT NULL DEFAULT 0,
	PRIMARY KEY("ID")
);
CREATE TABLE IF NOT EXISTS "VERSION" (
	"VERSION"	TEXT NOT NULL,
	PRIMARY KEY("VERSION")
);
INSERT INTO "tbl_FIELDS" VALUES ('SERVERNAME','Server Name (Max. 12)','SETTINGS','EN');
INSERT INTO "tbl_FIELDS" VALUES ('CLIENT_VERSIONS','Winget-Client Versions','SETTINGS','EN');
INSERT INTO "tbl_FIELDS" VALUES ('CLIENT_AUTHENTICATION','Client Authentication','SETTINGS','EN');
INSERT INTO "tbl_FIELDS" VALUES ('DNS_SERVER','DNS Server','SETTINGS','EN');
INSERT INTO "tbl_FIELDS" VALUES ('DNS_SUFFIX','Domain Suffix','SETTINGS','EN');
INSERT INTO "tbl_FIELDS" VALUES ('CLIENT_BP.ADD_CLIENT','Add Client','PERMISSIONS','EN');
INSERT INTO "tbl_FIELDS" VALUES ('CLIENT_BP.DELETE_CLIENT','Delete Client','PERMISSIONS','EN');
INSERT INTO "tbl_FIELDS" VALUES ('CLIENT_BP.INDEX','Client Overview','PERMISSIONS','EN');
INSERT INTO "tbl_FIELDS" VALUES ('GROUPS_BP.ADD_GROUP','Add Permission Group','PERMISSIONS','EN');
INSERT INTO "tbl_FIELDS" VALUES ('GROUPS_BP.DELETE_GROUP','Delete Permission Group','PERMISSIONS','EN');
INSERT INTO "tbl_FIELDS" VALUES ('GROUPS_BP.INDEX','Permission Overview','PERMISSIONS','EN');
INSERT INTO "tbl_FIELDS" VALUES ('GROUPS_BP.SAVE','Save Permissions','PERMISSIONS','EN');
INSERT INTO "tbl_FIELDS" VALUES ('SETTINGS_BP.INDEX','Settings Overview','PERMISSIONS','EN');
INSERT INTO "tbl_FIELDS" VALUES ('UI_BP.ADD_PACKAGE','Add Package','PERMISSIONS','EN');
INSERT INTO "tbl_FIELDS" VALUES ('UI_BP.ADD_PACKAGE_VERSION','Add Package Version','PERMISSIONS','EN');
INSERT INTO "tbl_FIELDS" VALUES ('UI_BP.DELETE_PACKAGE','Delete Package','PERMISSIONS','EN');
INSERT INTO "tbl_FIELDS" VALUES ('UI_BP.DELETE_PACKAGE_VERSION','Delete Package Version','PERMISSIONS','EN');
INSERT INTO "tbl_FIELDS" VALUES ('UI_BP.EDIT_PACKAGE','Edit Package','PERMISSIONS','EN');
INSERT INTO "tbl_FIELDS" VALUES ('USER_BP.ADD_USER','Add new User','PERMISSIONS','EN');
INSERT INTO "tbl_FIELDS" VALUES ('USER_BP.CHANGE_PASSWORD','Change User Passwords','PERMISSIONS','EN');
INSERT INTO "tbl_FIELDS" VALUES ('USER_BP.DELETE_USER','Delete User','PERMISSIONS','EN');
INSERT INTO "tbl_FIELDS" VALUES ('USER_BP.EDIT_USER','Edit User','PERMISSIONS','EN');
INSERT INTO "tbl_FIELDS" VALUES ('USER_BP.INDEX','User Overview','PERMISSIONS','EN');
INSERT INTO "tbl_FIELDS" VALUES ('CLIENT_BP','Client Management','PERMISSIONS','EN');
INSERT INTO "tbl_FIELDS" VALUES ('GROUPS_BP','Permission Management','PERMISSIONS','EN');
INSERT INTO "tbl_FIELDS" VALUES ('SETTINGS_BP','Settings','PERMISSIONS','EN');
INSERT INTO "tbl_FIELDS" VALUES ('UI_BP','Packages/Package Versions','PERMISSIONS','EN');
INSERT INTO "tbl_FIELDS" VALUES ('USER_BP','User Management','PERMISSIONS','EN');
INSERT INTO "tbl_FIELDS" VALUES ('SETTINGS_BP.EDIT_TERMS','Edit Terms of Service','PERMISSIONS','EN');
INSERT INTO "tbl_FIELDS" VALUES ('TOS','Enable Terms of Service','SETTINGS','EN');
INSERT INTO "tbl_FIELDS" VALUES ('CLIENT_BP.VIEW_LOGS','View Client Logs','PERMISSIONS','EN');
INSERT INTO "tbl_FIELDS" VALUES ('CLIENT_BP.BLACKLIST','Open Client Blacklist','PERMISSIONS','EN');
INSERT INTO "tbl_FIELDS" VALUES ('CLIENT_BP.BLOCK_CLIENT','Block Client','PERMISSIONS','EN');
INSERT INTO "tbl_FIELDS" VALUES ('STORE_BP','Package Store','PERMISSIONS','EN');
INSERT INTO "tbl_FIELDS" VALUES ('STORE_BP.INDEX','Store Overview','PERMISSIONS','EN');
INSERT INTO "tbl_FIELDS" VALUES ('STORE_BP.REFRESH_SOURCE','Update Winget Source DB','PERMISSIONS','EN');
INSERT INTO "tbl_FIELDS" VALUES ('STORE_BP.ADD_PACKAGE','Add Package from Store','PERMISSIONS','EN');
INSERT INTO "tbl_FIELDS" VALUES ('PACKAGE_STORE','Enable Package Store (Internet required)','SETTINGS','EN');
INSERT INTO "tbl_FIELDS" VALUES ('CLIENT_BP.CLEAR_LOGS','Clear Logs','PERMISSIONS','EN');
INSERT INTO "tbl_FIELDS" VALUES ('CLIENT_BP.BLACKLIST_GROUPS','Manage Blacklist-Groups','PERMISSIONS','EN');
INSERT INTO "tbl_FIELDS" VALUES ('CLIENT_BP.SETUP_CLIENT','Client Setup Page','PERMISSIONS','EN');
INSERT INTO "tbl_FIELDS" VALUES ('IP_RESTRICTION','Access for certain ips (Standard: DEFAULT)','SETTINGS','EN');
INSERT INTO "tbl_PACKAGES_LOCALE" VALUES (1,'en-US');
INSERT INTO "tbl_PACKAGES_LOCALE" VALUES (2,'de-DE');
INSERT INTO "tbl_PACKAGES_LOCALE" VALUES (3,'de-AT');
INSERT INTO "tbl_PACKAGES_LOCALE" VALUES (4,'de-CH');
INSERT INTO "tbl_PACKAGES_LOCALE" VALUES (5,'en-GB');
INSERT INTO "tbl_PACKAGES_LOCALE" VALUES (6,'en-CA');
INSERT INTO "tbl_PACKAGES_LOCALE" VALUES (7,'en-AU');
INSERT INTO "tbl_PACKAGES_LOCALE" VALUES (8,'fr-FR');
INSERT INTO "tbl_PACKAGES_LOCALE" VALUES (9,'fr-CA');
INSERT INTO "tbl_PACKAGES_LOCALE" VALUES (10,'fr-BE');
INSERT INTO "tbl_PACKAGES_LOCALE" VALUES (11,'es-ES');
INSERT INTO "tbl_PACKAGES_LOCALE" VALUES (12,'es-MX');
INSERT INTO "tbl_PACKAGES_LOCALE" VALUES (13,'it-IT');
INSERT INTO "tbl_PACKAGES_LOCALE" VALUES (14,'it-CH');
INSERT INTO "tbl_PACKAGES_LOCALE" VALUES (15,'pt-PT');
INSERT INTO "tbl_PACKAGES_LOCALE" VALUES (16,'pt-BR');
INSERT INTO "tbl_PACKAGES_LOCALE" VALUES (17,'ja-JP');
INSERT INTO "tbl_PACKAGES_LOCALE" VALUES (18,'ko-KR');
INSERT INTO "tbl_PACKAGES_LOCALE" VALUES (19,'zh-CN');
INSERT INTO "tbl_PACKAGES_LOCALE" VALUES (20,'zh-TW');
INSERT INTO "tbl_PACKAGES_LOCALE" VALUES (21,'ru-RU');
INSERT INTO "tbl_PACKAGES_LOCALE" VALUES (22,'ar-SA');
INSERT INTO "tbl_PACKAGES_LOCALE" VALUES (23,'nl-NL');
INSERT INTO "tbl_PACKAGES_LOCALE" VALUES (24,'pl-PL');
INSERT INTO "tbl_SETTINGS" VALUES ('SERVERNAME','Winget-Repo','TEXT',1,12,0);
INSERT INTO "tbl_SETTINGS" VALUES ('CLIENT_VERSIONS','1.8.0,1.9.0','TEXT',1,NULL,0);
INSERT INTO "tbl_SETTINGS" VALUES ('CLIENT_AUTHENTICATION','0','CHECKBOX',1,NULL,0);
INSERT INTO "tbl_SETTINGS" VALUES ('DNS_SERVER','192.168.1.1','IP',1,NULL,0);
INSERT INTO "tbl_SETTINGS" VALUES ('DNS_SUFFIX','DUMMY','TEXT',1,NULL,0);
INSERT INTO "tbl_SETTINGS" VALUES ('TOS','0','CHECKBOX',1,NULL,0);
INSERT INTO "tbl_SETTINGS" VALUES ('PACKAGE_STORE','0','CHECKBOX',1,NULL,1);
INSERT INTO "tbl_SETTINGS" VALUES ('VERSION_COUNTER','2.6.8','TEXT',0,NULL,0);
INSERT INTO "tbl_SETTINGS" VALUES ('IP_RESTRICTION','DEFAULT','TEXT',1,NULL,0);
INSERT INTO "tbl_TEXTS" VALUES ('TOS',NULL);
INSERT INTO "tbl_USER_RIGHTS" VALUES ('f4b8b5af-a414-466f-aad9-184e7e386425','Admin',1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1);
INSERT INTO "tbl_USER_RIGHTS" VALUES ('6ae8e343-3105-4df9-a3a0-02384cde6251','User',0,0,0,0,0,1,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0);
INSERT INTO "VERSION" VALUES ('1.0');
COMMIT;
